### ISSUE TITLE
suggestion: use folders

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [earthlng/FFprefs-diffs#1]
Would be prudent to use folders in your root dir? This would have a couple of benefits

- Allow separation of various builds such as windows/linux/ESR
- Stop the home page directory listing ending up full of 100's of items, shoving the readme was way way down the page

**Comment by earthlng** [comment]
Yeah good point, thx. I was thinking about using different branches for different versions which would make it easier to compare them. The filenames would be the same for Windows/Linux/Mac. But I'm not doing Linux and Mac versions anytime soon, but will keep it in mind.
I plan to do ESR diffs in the future and will put those in an ESR folder.

**Comment by Thorin-Oakenpants** [comment]
Not sure if you know or not, but to create a folder from the web interface, just go "create new file" but use `/foldername/filename.ext` instead of just `filename.ext`

**Comment by earthlng** [comment]
thx, already figured that one out :)

**Comment by Thorin-Oakenpants** [comment]
This is Major Pants to Earth Control ... why is it so quiet?

**Comment by Thorin-Oakenpants** [comment]
duuuuude ... nice ... https://bugzilla.mozilla.org/show_bug.cgi?id=1397996#c2

Delete after reading

**Comment by earthlng** [comment]
NOICE. But it's useless unless they make that the default behaviour in FF. If you do this now you'll be in a very small group of people with scrollbar height/width 0. And remember that the guy who came up with that trick said he has like 10 more of these, so it's most likely still possible to detect your OS.

delete after reading

**Comment by Thorin-Oakenpants** [comment]
Yes, I know about the entropy. It was a test.
