### ISSUE TITLE
font.name.* prefs will all be set to "" in FF55+

### ISSUE THREAD

**Issue by earthlng** [earthlng/FFprefs-diffs#2]
that should result in ~106 less prefs in the Windows vs Linux vs Mac diffs

```
Needs "auto" pseudo font family to specify default font in font setting dialog
RESOLVED FIXED in Firefox 55
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1344990

[modules/libpref/init/all.js changes](https://hg.mozilla.org/mozilla-central/rev/2b99ea907d3d)

**Comment by Thorin-Oakenpants** [comment]
FYI: What is Arthur up to? - [clicky](https://bugzilla.mozilla.org/buglist.cgi?bug_status=__open__&email1=arthuredelstein%40gmail.com&emailcc1=1&emailtype1=exact&list_id=13694725)  ... and where has he been? [clicky](https://bugzilla.mozilla.org/buglist.cgi?bug_status=__closed__&email1=arthuredelstein%40gmail.com&emailcc1=1&emailtype1=exact&list_id=13694727)

Please delete after reading - thanks
